include("test_helpers.jl")
include("test_paircopulas.jl")
include("test_extreme_value.jl")
include("test_archimedean_inverse.jl")
include("test_survival.jl")
include("test_vines_mixed.jl")
include("test_vines_truncated.jl")
include("test_core.jl")
